package org.firstinspires.ftc.teamcode;


import com.qualcomm.robotcore.eventloop.opmode.OpMode;

public class AutoOpMode extends OpMode {

    GhostController ghostController = new GhostController("AutoGeneratedOpMode");

    public void init(){

    }

    public void loop(){
        ghostController.update();

        ghostController.leftStickY();
        ghostController.leftStickX();
        ghostController.rightStickY();
        ghostController.rightStickX();

        ghostController.buttonX();
        ghostController.buttonA();
        ghostController.buttonB();
        ghostController.buttonY();

        ghostController.dpadUp();
        ghostController.dpadDown();
        ghostController.dpadLeft();
        ghostController.dpadRight();

        ghostController.rightbumper();
        ghostController.leftbumper();
    }

}
